import { useState, useRef } from 'react';
import { motion, AnimatePresence, useInView } from 'framer-motion';

const FAQSection = () => {
  const sectionRef = useRef(null);
  const isInView = useInView(sectionRef, { once: true, margin: "-100px" });
  
  const faqs = [
    {
      question: "How does the AI content generator work?",
      answer: "Our AI content generator uses advanced machine learning algorithms trained on diverse writing styles to create high-quality content. Simply input your topic, select your desired tone and format, and our AI will generate unique content tailored to your specifications in seconds."
    },
    {
      question: "Is the content generated by AI original and plagiarism-free?",
      answer: "Yes, all content created by our AI is 100% original and plagiarism-free. Our system generates unique content for each request and doesn't copy from existing sources. We recommend running the content through a plagiarism checker for your peace of mind."
    },
    {
      question: "Can I edit the AI-generated content?",
      answer: "Absolutely! All generated content can be edited using our built-in editor. You can refine, expand, or modify the content to perfectly match your brand voice and requirements. Our editor also includes grammar checking and style suggestions to help polish your content."
    },
    {
      question: "What types of content can I create with this tool?",
      answer: "Our AI content generator supports a wide range of content types including blog posts, social media updates, email newsletters, product descriptions, ad copy, website content, video scripts, and more. We're constantly adding new content types and templates."
    },
    {
      question: "Do you offer a free trial?",
      answer: "Yes, we offer a 14-day free trial on all our plans. No credit card is required to start your trial, and you'll have access to most features to test the platform before committing to a subscription."
    },
    {
      question: "How do I cancel my subscription?",
      answer: "You can cancel your subscription at any time from your account settings. If you cancel, you'll still have access to the platform until the end of your current billing period. We don't offer refunds for partial months."
    }
  ];

  return (
    <section id="faq" className="py-20 bg-gray-50">
      <div className="container mx-auto px-4 md:px-6">
        <div ref={sectionRef} className="text-center mb-16">
          <motion.span 
            className="text-primary font-semibold"
            initial={{ opacity: 0 }}
            animate={isInView ? { opacity: 1 } : { opacity: 0 }}
            transition={{ duration: 0.5 }}
          >
            FAQ
          </motion.span>
          <motion.h2 
            className="text-3xl md:text-4xl font-bold mt-2 mb-4"
            initial={{ opacity: 0, y: 20 }}
            animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
            transition={{ duration: 0.5, delay: 0.2 }}
          >
            Frequently Asked Questions
          </motion.h2>
          <motion.p 
            className="text-xl text-gray-600 max-w-3xl mx-auto"
            initial={{ opacity: 0, y: 20 }}
            animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
            transition={{ duration: 0.5, delay: 0.4 }}
          >
            Everything you need to know about our AI content generator. Can't find the answer you're looking for? Contact our support team.
          </motion.p>
        </div>
        
        <div className="max-w-3xl mx-auto">
          {faqs.map((faq, index) => (
            <FAQItem
              key={index}
              question={faq.question}
              answer={faq.answer}
              index={index}
            />
          ))}
        </div>
      </div>
    </section>
  );
};

interface FAQItemProps {
  question: string;
  answer: string;
  index: number;
}

const FAQItem = ({ question, answer, index }: FAQItemProps) => {
  const [isOpen, setIsOpen] = useState(false);
  const itemRef = useRef(null);
  const isInView = useInView(itemRef, { once: true, margin: "-100px" });
  
  return (
    <motion.div
      ref={itemRef}
      className="mb-4 border-b border-gray-200 pb-4"
      initial={{ opacity: 0, y: 20 }}
      animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 20 }}
      transition={{ duration: 0.5, delay: index * 0.1 + 0.5 }}
    >
      <button
        className="flex justify-between items-center w-full text-left py-4 focus:outline-none"
        onClick={() => setIsOpen(!isOpen)}
      >
        <h3 className="text-lg font-medium text-gray-900">{question}</h3>
        <motion.span
          animate={{ rotate: isOpen ? 180 : 0 }}
          transition={{ duration: 0.3 }}
          className="text-primary"
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <polyline points="6 9 12 15 18 9"></polyline>
          </svg>
        </motion.span>
      </button>
      
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3 }}
            className="overflow-hidden"
          >
            <p className="text-gray-600 pb-4">{answer}</p>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

export default FAQSection;
